import { NgModule } from '@angular/core';
import { CdkTableModule } from "@angular/cdk/table"

import {
  MatDialogModule,
  MatButtonModule,
  MatCardModule,
  MatInputModule,
  MatProgressSpinnerModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatSidenavModule,
  MatMenuModule,
  MatToolbarModule,
  MatCheckboxModule,
  MatSliderModule,
  MatProgressBarModule,
  MatTabsModule,
  MatPaginatorModule,
  MatTableModule,
  MatListModule,
  MatChipsModule,
  MatRadioModule,
  MatSelectModule,
  MatTooltipModule,
  MatSnackBarModule,
} from "@angular/material"

@NgModule({
  imports: [
    MatDialogModule,
    MatButtonModule,
    MatCardModule,
    MatInputModule,
    MatProgressSpinnerModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSidenavModule,
    MatMenuModule,
    MatToolbarModule,
    MatCheckboxModule,
    MatSliderModule,
    MatProgressBarModule,
    MatTabsModule,
    MatPaginatorModule,
    MatTableModule,
    MatListModule,
    MatChipsModule,
    MatRadioModule,
    MatSelectModule,
    MatTooltipModule,
    MatSnackBarModule,
    CdkTableModule
  ],
  exports: [
    MatDialogModule,
    MatButtonModule,
    MatCardModule,
    MatInputModule,
    MatProgressSpinnerModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSidenavModule,
    MatMenuModule,
    MatToolbarModule,
    MatCheckboxModule,
    MatSliderModule,
    MatProgressBarModule,
    MatTabsModule,
    MatPaginatorModule,
    MatTableModule,
    MatListModule,
    MatChipsModule,
    MatRadioModule,
    MatSelectModule,
    MatTooltipModule,
    MatSnackBarModule,
    CdkTableModule
  ]
})

export class MaterialModule { }
